-- 2025.06.04
WITH PP AS (
    SELECT *,(SELECT D.PARENT_ID FROM ECOLI_DATA D WHERE E.PARENT_ID = D.ID)  AS PPARENT_ID
    FROM ECOLI_DATA E
)

SELECT ID
FROM PP
WHERE PPARENT_ID IS NOT NULL AND (SELECT D.PARENT_ID FROM ECOLI_DATA D WHERE PP.PPARENT_ID = D.ID) IS NULL;