-- 2024.07.07
SELECT DISTINCT info.ITEM_ID, info.ITEM_NAME, info.RARITY
FROM ITEM_INFO info LEFT JOIN ITEM_TREE tree
ON info.ITEM_ID = tree.PARENT_ITEM_ID
WHERE tree.PARENT_ITEM_ID IS NULL
ORDER BY info.ITEM_ID DESC;