-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(SALES_AMOUNT) * product.PRICE AS SALES
FROM PRODUCT product INNER JOIN OFFLINE_SALE sale
ON product.PRODUCT_ID = sale.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;