-- 2025.04.30
WITH AVG_REVIEW AS (
  SELECT REST_ID, AVG(REVIEW_SCORE) AS SCORE
  FROM REST_REVIEW 
  GROUP BY REST_ID
)

SELECT info.REST_ID, info.REST_NAME, info.FOOD_TYPE, info.FAVORITES, info.ADDRESS, ROUND(review.SCORE, 2) AS SCORE
FROM REST_INFO info JOIN AVG_REVIEW review
ON info.REST_ID = review.REST_ID
WHERE info.ADDRESS LIKE '서울%'
ORDER BY review.SCORE DESC, info.FAVORITES DESC;