-- 2025.03.14
SELECT COUNT(name.FISH_NAME) AS FISH_COUNT, name.FISH_NAME
FROM FISH_INFO info JOIN FISH_NAME_INFO name
ON info.FISH_TYPE = name.FISH_TYPE
GROUP BY name.FISH_NAME
ORDER BY COUNT(name.FISH_NAME) DESC;