-- 2025.06.04
WITH ONLINE_2021 AS (
    SELECT o.ONLINE_SALE_ID, o.USER_ID, o.PRODUCT_ID, o.SALES_AMOUNT, o.SALES_DATE
    FROM ONLINE_SALE o INNER JOIN USER_INFO u
    ON o.USER_ID = u.USER_ID
    WHERE YEAR(u.JOINED) = '2021'
)

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = '2021') , 1) AS PURCHASED_RATIO
FROM ONLINE_2021
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH;