-- 2025.06.04
SELECT APP.APNT_NO, PT.PT_NAME, PT.PT_NO, APP.MCDP_CD, DT.DR_NAME, APP.APNT_YMD
FROM APPOINTMENT APP JOIN PATIENT PT
    ON APP.PT_NO = PT.PT_NO
    JOIN DOCTOR DT
    ON APP.MDDR_ID = DT.DR_ID
WHERE APP.MCDP_CD = 'CS' AND APP.APNT_CNCL_YN = 'N' AND DATE_FORMAT(APP.APNT_YMD, '%Y-%m-%d') = '2022-04-13' 
ORDER BY APP.APNT_YMD;