-- 2025.05.07
WITH FRONTEND_SKILL
AS (
    SELECT SUM(CODE) AS SUM_CODE
    FROM SKILLCODES 
    WHERE CATEGORY = 'Front End'
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS INNER JOIN FRONTEND_SKILL
ON SKILL_CODE & FRONTEND_SKILL.SUM_CODE >= 1
ORDER BY ID;