-- 2025.03.29
SELECT eco1.ID, eco1.GENOTYPE, eco2.GENOTYPE AS 'PARENT_GENOTYPE'
FROM ECOLI_DATA eco1 JOIN ECOLI_DATA eco2
ON eco1.PARENT_ID = eco2.ID
WHERE eco1.GENOTYPE & eco2.GENOTYPE = eco2.GENOTYPE
ORDER BY eco1.ID;

