-- 2024.07.30
SELECT DISTINCT car.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR car INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY history
ON car.CAR_ID = history.CAR_ID
WHERE car.CAR_TYPE = '세단' AND MONTH(history.START_DATE) = '10'
ORDER BY car.CAR_ID DESC;