-- 2024.07.06
SELECT SUM(SCORE) AS SCORE, em.EMP_NO, em.EMP_NAME, em.POSITION, em.EMAIL
FROM HR_EMPLOYEES em INNER JOIN HR_GRADE grade
ON em.EMP_NO = grade.EMP_NO
GROUP BY grade.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
