-- 2024.07.07
SELECT depart.DEPT_ID, depart.DEPT_NAME_EN, ROUND(AVG(em.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT depart JOIN HR_EMPLOYEES em
ON depart.DEPT_ID = em.DEPT_ID
GROUP BY DEPT_ID
ORDER BY AVG(em.SAL) DESC;