-- 2025.06.04
SELECT CASE WHEN (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') & SKILL_CODE > 0 AND (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') & SKILL_CODE > 0 THEN 'A'
            WHEN (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') & SKILL_CODE > 0 THEN 'B'
            WHEN (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') & SKILL_CODE > 0 THEN 'C'
            ELSE 'D'
            END AS GRADE, ID, EMAIL
FROM DEVELOPERS
HAVING GRADE IN ('A', 'B', 'C')
ORDER BY GRADE, ID;